Repository MyOnlineStore/public-api-docs, pull requests merged in 2020-10, with the labels that each got.

#22 Upgrade Packages
  package-lock.json
  package.json
Labels: dependencies

#24 CASH-1660 Announced removal of payment provider ID and paytype ID in changelog
  spec/openapi.yaml
  web/swagger-docs/changelog.md
Labels: good first issue

#25 Fix security info for PartnerToken only endpoints
  spec/openapi.yaml
Labels: bug
